blockstream:
  client-id: Input your ID
  client-secret: Input your secret
  token-url: https://login.blockstream.com/realms/blockstream-public/protocol/openid-connect/token
  api-url: https://enterprise.blockstream.info/api


etherscan:
  api-key: MJQ2CWTI2395PZGY75ZQ8N6Y1NS53JVH8G
  base-url: https://api.etherscan.io/api