blockstream:
  client-id: eeb1a2e3-5a75-4f13-81db-0af024067f5a
  client-secret: FOkd1yYZYLoQ8ayLJNEqiHjmZUvYodqe
  token-url: https://login.blockstream.com/realms/blockstream-public/protocol/openid-connect/token
  api-url: https://enterprise.blockstream.info/api


etherscan:
  api-key: MJQ2CWTI2395PZGY75ZQ8N6Y1NS53JVH8G
  api-url: https://api.etherscan.io/api