blockstream:
  client-id: 2cc2811d-74a5-4970-918a-b8852a59b851
  client-secret: vDDt3DrCBCazPQ5lcVYAGBMnufa9QBa0
  token-url: https://login.blockstream.com/realms/blockstream-public/protocol/openid-connect/token
  api-url: https://enterprise.blockstream.info/api


etherscan:
  api-key: MJQ2CWTI2395PZGY75ZQ8N6Y1NS53JVH8G
  api-url: https://api.etherscan.io/api